---
- name: restart mct
  service: name="mct-{{item.key}}" state=restarted

- name: restart mct development
  service: name=mct-development state=restarted
  
- name: restart nginx
  service: name=nginx state=reloaded
