---
- name: restart mct production
  service: name=mct-production state=restarted

- name: restart mct development
  service: name=mct-development state=restarted
  
- name: restart nginx
  service: name=nginx state=reloaded
