---
- name: Install deps.
  apt: name="{{item}}" state=installed
  with_items:
    - nginx
    - postgresql
    - postgresql-server-dev-9.3
    - python-psycopg2

- git: repo=https://github.com/mojoconf/MCT dest="{{mct_app_home}}-{{item.key}}"
  sudo_user: "{{mct_app_user}}"
  sudo: yes
  with_dict: mct_envs
  tags: [ webapp ]

- file: path="{{mct_app_home}}-{{item.key}}/log" owner={{mct_postgres_user}} state=directory mode=0755
  with_dict: mct_envs
  notify: restart mct
  tags: [ webapp, log ]

- template: src="logrotate.j2" dest="/etc/logrotate.d/{{mct_app}}-{{item.key}}"
  with_dict: mct_envs
  tags: [ log ]

- name: Install deps
  shell: "{{plenv_root}}/shims/cpanm --installdeps {{mct_app_home}}-{{item.key}}"
  with_dict: mct_envs
  register: cpanm_install
  changed_when: cpanm_install.stdout | match('distributions*\sinstalled')
  notify: restart mct
  tags: [ webapp ]

- postgresql_user: name="{{mct_postgres_user}}" password="{{mct_postgres_pass}}"
  sudo_user: postgres
  sudo: yes
  
- postgresql_db: owner="{{mct_postgres_user}}" name="mct_{{item.key}}"
  with_dict: mct_envs
  sudo_user: postgres
  sudo: yes
  tags: [ webapp ]

- template: src="mct.conf.j2" dest="{{mct_app_home}}-{{item.key}}/mct.{{item.key}}.conf"
  with_dict: mct_envs
  tags: [ config, webapp ]

- template: src=mct-upstart.conf.j2 dest="/etc/init/{{mct_app}}-{{item.key}}.conf" owner=root mode=0644
  with_dict: mct_envs
  tags: [ config ]

- copy: src=deploy dest=/usr/local/bin/deploy owner=root group=ops mode=0755
  tags: [ deploy ]

- service: name="{{mct_app}}-{{item.key}}" state=started enabled=yes
  with_dict: mct_envs
  tags: [ webapp ]

- template: src=mct-nginx.conf.j2 dest="/etc/nginx/sites-available/{{mct_app}}-{{item.key}}.conf" owner=root mode=0644
  with_dict: mct_envs
  notify: restart nginx
  tags: [ nginx ]

- name: Setup link 
  file: state=link path="/etc/nginx/sites-enabled/{{mct_app}}-{{item.key}}.conf" src="/etc/nginx/sites-available/{{mct_app}}-{{item.key}}.conf" owner=root
  with_dict: mct_envs
  notify: restart nginx
  tags: [ nginx ]

- command: nginx -t -c /etc/nginx/nginx.conf
  tags: [ nginx ]
