#!/bin/sh
MODE="$1";
BRANCH=${2:-master};
RUN_AS="www";
SELF=$(readlink -f $0);

run () {
  echo "\$ $@";
  $@;
  echo "------------------------------------------------------------------- \$?=$?";
  echo;
}

[ -z $MODE ] && echo "Usage: $0 <production|development> [branch]" && exit 1;
[ "x$USER" = "x$RUN_AS" ] || exec sudo -i -u $RUN_AS $SELF $MODE;

if [ "x$MODE" = "xstatus" ]; then
  for m in development production; do
    cd /home/www/mct-$m;
    echo "$m:";
    git log HEAD^..HEAD --pretty=format:'%Cgreen%ci %Cred%h%Creset %s %Cgreen%C(bold blue)<%an>%Creset %C(yellow)%d%Creset';
    echo;
  done
  exit;
fi

run cd /home/www/mct-$MODE;
run git remote update;
run git checkout -f -B master origin/master;
run cpanm --installdeps .;

export MOJO_CONFIG="/home/www/mct-$MODE/mct.$MODE.conf";
run hypnotoad /home/www/mct-$MODE/script/mct
